import { Injectable } from '@angular/core';
import { AutoscrollCategoryModel } from '../models/autoScrollCategory.model';

@Injectable({
  providedIn: 'root'
})
export class AutoscrollCategoryService {
  private products: AutoscrollCategoryModel[] = [
       {
      id: 1,
      name: "Premium Cotton Fabric",
      description: "High-quality 100% cotton fabric perfect for clothing and home textiles.",
      price: 12.99,
      originalPrice: 15.99,
      category: "Cotton Fabric",
      supplier: "TexFab India",
      stock: 150,
      unit: "yard",
      imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=400&q=80",
      rating: 4.8,
      reviews: 124,
      colors: ["White", "Blue", "Red"],
      material: "Cotton",
      weight: "200 GSM",
      width: "60 inches",
      attributes: ["Breathable", "Soft", "Durable"],
      discount: 10
    },
    {
      id: 2,
      name: "Organic Cotton Fabric",
      description: "GOTS certified organic cotton fabric for eco-friendly clothing.",
      price: 15.99,
      originalPrice: 19.99,
      category: "Cotton Fabric",
      supplier: "Organic Looms",
      stock: 85,
      unit: "yard",
      imageUrl: "https://images.unsplash.com/photo-1534215754734-18e55d13e346?auto=format&fit=crop&w=400&q=80",
      rating: 4.5,
      reviews: 92,
      colors: ["White", "Green", "Beige"],
      material: "Cotton",
      weight: "180 GSM",
      width: "58 inches",
      attributes: ["Organic", "Eco-friendly", "Hypoallergenic"],
      discount: 20
    },
        {
      id: 3,
      name: "Premium Cotton Fabric",
      description: "High-quality 100% cotton fabric perfect for clothing and home textiles.",
      price: 12.99,
      originalPrice: 15.99,
      category: "Cotton Fabric",
      supplier: "TexFab India",
      stock: 150,
      unit: "yard",
      imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=400&q=80",
      rating: 4.8,
      reviews: 124,
      colors: ["White", "Blue", "Red"],
      material: "Cotton",
      weight: "200 GSM",
      width: "60 inches",
      attributes: ["Breathable", "Soft", "Durable"],
      discount: 10
    },
    {
      id: 4,
      name: "Organic Cotton Fabric",
      description: "GOTS certified organic cotton fabric for eco-friendly clothing.",
      price: 15.99,
      originalPrice: 19.99,
      category: "Cotton Fabric",
      supplier: "Organic Looms",
      stock: 85,
      unit: "yard",
      imageUrl: "https://images.unsplash.com/photo-1534215754734-18e55d13e346?auto=format&fit=crop&w=400&q=80",
      rating: 4.5,
      reviews: 92,
      colors: ["White", "Green", "Beige"],
      material: "Cotton",
      weight: "180 GSM",
      width: "58 inches",
      attributes: ["Organic", "Eco-friendly", "Hypoallergenic"],
      discount: 20
    },
    {
      id: 5,
      name: "Cotton Poplin Fabric",
      description: "Smooth and crisp cotton poplin for shirts and dresses.",
      price: 14.50,
      originalPrice: 17.99,
      category: "Cotton Fabric",
      supplier: "Global Fabrics",
      stock: 120,
      unit: "yard",
      imageUrl: "https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?auto=format&fit=crop&w=400&q=80",
      rating: 4.6,
      reviews: 78,
      colors: ["White", "Blue", "Pink"],
      material: "Cotton",
      weight: "140 GSM",
      width: "44 inches",
      attributes: ["Smooth", "Crisp", "Lightweight"],
      discount: 30
    },
    {
      id: 6,
      name: "Cotton Jersey Fabric",
      description: "Soft stretchy cotton jersey for comfortable apparel.",
      price: 11.99,
      originalPrice: 14.99,
      category: "Cotton Fabric",
      supplier: "WeaveWorld",
      stock: 95,
      unit: "yard",
      imageUrl: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=400&q=80",
      rating: 4.3,
      reviews: 65,
      colors: ["Black", "Navy Blue", "Gray"],
      material: "Cotton Lycra",
      weight: "180 GSM",
      width: "60 inches",
      attributes: ["Stretchy", "Soft", "Comfortable"],
      discount: 40
    },

    // Silk Fabric Products (3 items)
    {
      id: 7,
      name: "Pure Silk Fabric",
      description: "Luxurious pure silk fabric with natural sheen.",
      price: 45.99,
      originalPrice: 59.99,
      category: "Silk Fabric",
      supplier: "SilkMart",
      stock: 42,
      unit: "yard",
      imageUrl: "https://images.unsplash.com/photo-1534215754734-18e55d13e346?auto=format&fit=crop&w=400&q=80",
      rating: 4.9,
      reviews: 215,
      colors: ["White", "Black", "Navy Blue"],
      material: "Silk",
      weight: "16 momme",
      width: "45 inches",
      attributes: ["Luxurious", "Breathable", "Hypoallergenic"],
      discount: 50
    },
    {
      id: 8,
      name: "Silk Satin Fabric",
      description: "Lustrous silk satin with a smooth finish.",
      price: 52.50,
      originalPrice: 65.00,
      category: "Silk Fabric",
      supplier: "Elegant Textiles",
      stock: 35,
      unit: "yard",
      imageUrl: "https://images.unsplash.com/photo-1566140967404-b8b3932483f5?auto=format&fit=crop&w=400&q=80",
      rating: 4.8,
      reviews: 178,
      colors: ["White", "Red", "Purple"],
      material: "Silk",
      weight: "19 momme",
      width: "54 inches",
      attributes: ["Lustrous", "Smooth", "Elegant"],
      discount: 60
    },
    {
      id: 9,
      name: "Dupioni Silk Fabric",
      description: "Textured dupioni silk with slubbed appearance.",
      price: 38.99,
      originalPrice: 48.99,
      category: "Silk Fabric",
      supplier: "SilkMart",
      stock: 28,
      unit: "yard",
      imageUrl: "https://images.unsplash.com/photo-1604176354204-9268737828e4?auto=format&fit=crop&w=400&q=80",
      rating: 4.7,
      reviews: 142,
      colors: ["Gold", "Olive", "Rust"],
      material: "Silk",
      weight: "22 momme",
      width: "45 inches",
      attributes: ["Textured", "Slubbed", "Rich"],
      discount: 70
    },

    // Linen Fabric Products (2 items)
    {
      id: 10,
      name: "European Linen Fabric",
      description: "Premium European linen fabric with natural texture.",
      price: 22.50,
      originalPrice: 28.00,
      category: "Linen Fabric",
      supplier: "Elegant Textiles",
      stock: 67,
      unit: "yard",
      imageUrl: "https://images.unsplash.com/photo-1566140967404-b8b3932483f5?auto=format&fit=crop&w=400&q=80",
      rating: 4.7,
      reviews: 178,
      colors: ["White", "Olive", "Natural"],
      material: "Linen",
      weight: "250 GSM",
      width: "55 inches",
      attributes: ["Breathable", "Strong", "Absorbent"],
      discount: 80
    },
    {
      id: 11,
      name: "Linen Blend Fabric",
      description: "Linen-cotton blend for softer texture.",
      price: 18.99,
      originalPrice: 23.50,
      category: "Linen Fabric",
      supplier: "Global Fabrics",
      stock: 89,
      unit: "yard",
      imageUrl: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=400&q=80",
      rating: 4.5,
      reviews: 112,
      colors: ["Beige", "Cream", "Dusty Pink"],
      material: "Linen",
      weight: "220 GSM",
      width: "58 inches",
      attributes: ["Soft", "Breathable", "Wrinkle-resistant"],
      discount: 90
    },
       {
      id: 12,
      name: "Linen Blend Fabric",
      description: "Linen-cotton blend for softer texture.",
      price: 18.99,
      originalPrice: 23.50,
      category: "Linen Fabric",
      supplier: "Global Fabrics",
      stock: 89,
      unit: "yard",
      imageUrl: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=400&q=80",
      rating: 4.5,
      reviews: 112,
      colors: ["Beige", "Cream", "Dusty Pink"],
      material: "Linen",
      weight: "220 GSM",
      width: "58 inches",
      attributes: ["Soft", "Breathable", "Wrinkle-resistant"],
      discount: 90
    },

    // ... add remaining products here without duplicates
  ];

  // Correct return type here!
  getAllCategory(): AutoscrollCategoryModel[] {
    return this.products;
  }
}
